name: chat_app_asper
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.21.0
  firebase_auth: ^3.6.4
  firebase_storage: ^10.3.6
  image_picker: ^0.8.5+3
  image_cropper: ^3.0.0
  flutter_native_splash: ^2.2.7
  google_fonts: ^3.0.1
  animated_splash_screen: ^1.3.0
  another_flushbar: ^1.10.29
  firebase_app_check: ^0.0.6+20
  google_sign_in: ^5.4.1
  font_awesome_flutter: ^10.1.0
  cloud_firestore: ^3.4.5
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
